;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        js2-mode-show-node
        keyboard-escape-quit
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        mouse-buffer-menu
        switch-to-buffer
        toggle-frame-maximized
        ))
