;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua--prefix-override-handler
        js2-mode-show-node
        keyboard-escape-quit
        ))

(setq mc/cmds-to-run-once
      '(
        cua-exchange-point-and-mark
        cua-paste
        helm-M-x
        mark-whole-buffer
        mouse-buffer-menu
        switch-to-buffer
        toggle-frame-maximized
        ))
